### ISSUE TITLE
inferno is not used anywhere troughout the codebase-how is that?

### ISSUE THREAD

**Issue by capaj** [vinej/inferno-mobx-remux-starter#1]
I was looking for a boilerplate to use mobx with inferno, but this is just plain misleading.

**Comment by vinej** [comment]
If you want to use only 'Mobx' with Inferno, you're right, it could be misleading, but without Mobx-react, mobx alone is very hard to use with Inferno. 'Mobx-react' do the link between the components and the data.

Inferno has the 'inferno-compat' package to help people to use a React code base with Inferno. In the **package.json** you will see all the 'inferno package' and in the **`webpack.config.js**' you have some aliases to translate react imports into inferno.imports.

Like that you can use almost the same code with React and Inferno. The goal was to replicate the https://github.com/vinej/react-remux example for Inferno. With the 'inferno-compat' you can also use some react libraries like Mobx-react that is very usefull with Mobx. Without it it's very difficult to get the most of Mobx.

The current version was working with inferno 0.7.15, but the version 0.7.17 is broken related to an open issue about the 'inferno-router`and the 'ìnferno-compat' package.

For now, I just fixed the code to use version 0.7.15 and It's working again.Just get the latest version and reinstall.

When the ìnferno-router' isssue is resolved, the code base will be almost like the React version but using the Inferno libraries.

I hope I answered to your question

Thanks

**Comment by capaj** [comment]
@vinej Sorry, I did not notice ìnferno-compat. Wasn't even aware somthing like that exists. The bug where inferno needs to be imported complicates it further.
